name: Run Cycle

on:
  schedule:
    - cron: '*/5 * * * *' 
  workflow_dispatch:

jobs:
  run-cycle-job:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Cache Python packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install dependencies from requirements.txt
    
    - name: Run cycle function
      env:
        SEMANTIC_KEY: ${{ secrets.SEMANTIC_KEY }}
        GPT_KEY: ${{ secrets.GPT_KEY }}
      run: |
        python snowball_samples.py --SEMANTIC_KEY="${SEMANTIC_KEY}" --GPT_KEY="${GPT_KEY}"

    - name: Commit changes
      run: |
        git add .
        git commit -m "Cycle Data Update"   

    - name: Push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git push origin main